import type { Property } from "@/types/property";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "mock-1",
    hash: "h1",
    title: "Luxury 5 Bedroom Detached Duplex with BQ",
    listingUrl: "https://www.propertypro.ng/listing/1",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 150000000,
    priceCurrency: "NGN",
    bedrooms: 5,
    bathrooms: 5,
    area: "Lekki Phase 1",
    state: "Lagos",
    country: "Nigeria",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Detached Duplex",
    description: "Exquisitely finished 5 bedroom detached duplex with swimming pool, BQ, and modern finishes throughout. Located in a serene estate in Lekki Phase 1.",
    features: ["Swimming Pool", "BQ", "Central AC", "CCTV", "Smart Home"],
    landSizeSqm: 600,
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=800&auto=format&fit=crop"],
    agentVerified: true,
    viewCount: 120,
    inquiryCount: 15,
    favoriteCount: 45,
    isPremium: true,
    isFeatured: true,
    isHotDeal: true,
    currentVersion: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    qualityScore: 95,
    security: [],
    utilities: [],
    landmarks: [],
    searchKeywords: [],
    promoTags: [],
  },
  {
    id: "mock-2",
    hash: "h2",
    title: "3 Bedroom Flat in Ikeja GRA",
    listingUrl: "https://nigeriapropertycentre.com/listing/2",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "RENT",
    category: "RESIDENTIAL",
    price: 3500000,
    priceCurrency: "NGN",
    bedrooms: 3,
    bathrooms: 3,
    area: "Ikeja GRA",
    state: "Lagos",
    country: "Nigeria",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Flat/Apartment",
    rentFrequency: "per annum",
    description: "Well maintained 3 bedroom flat in a quiet cul-de-sac in Ikeja GRA. All rooms en-suite with fitted kitchen.",
    features: ["Fitted Kitchen", "24hr Power", "Security"],
    landSizeSqm: 150,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=800&auto=format&fit=crop"],
    agentVerified: true,
    viewCount: 85,
    inquiryCount: 8,
    favoriteCount: 20,
    isPremium: false,
    isFeatured: false,
    isHotDeal: false,
    currentVersion: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    qualityScore: 88,
    security: [],
    utilities: [],
    landmarks: [],
    searchKeywords: [],
    promoTags: [],
  },
  {
    id: "mock-3",
    hash: "h3",
    title: "Brand New 4 Bedroom Semi-Detached Duplex",
    listingUrl: "https://www.privateproperty.com.ng/listing/3",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 85000000,
    priceCurrency: "NGN",
    bedrooms: 4,
    bathrooms: 4,
    area: "Ajah",
    state: "Lagos",
    country: "Nigeria",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Semi-Detached Duplex",
    description: "Brand new 4 bedroom semi-detached duplex in a gated estate. Quality finishes, spacious rooms, and excellent road network.",
    features: ["Gated Estate", "Paved Roads", "BQ", "Car Park"],
    landSizeSqm: 350,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop"],
    agentVerified: true,
    viewCount: 210,
    inquiryCount: 22,
    favoriteCount: 56,
    isPremium: true,
    isFeatured: false,
    isHotDeal: false,
    currentVersion: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    qualityScore: 92,
    security: [],
    utilities: [],
    landmarks: [],
    searchKeywords: [],
    promoTags: [],
  },
  {
    id: "mock-4",
    hash: "h4",
    title: "Commercial Office Space in Victoria Island",
    listingUrl: "https://www.propertypro.ng/listing/4",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "LEASE",
    category: "COMMERCIAL",
    price: 15000000,
    priceCurrency: "NGN",
    area: "Victoria Island",
    state: "Lagos",
    country: "Nigeria",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Office Space",
    rentFrequency: "per annum",
    description: "Premium office space on Adeola Odeku Street, Victoria Island. Open plan layout, 24/7 power, and dedicated parking.",
    features: ["24/7 Power", "Elevator", "Reception", "Conference Room", "Parking"],
    buildingSizeSqm: 500,
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop"],
    agentVerified: true,
    viewCount: 150,
    inquiryCount: 5,
    favoriteCount: 12,
    isPremium: false,
    isFeatured: true,
    isHotDeal: false,
    currentVersion: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    qualityScore: 85,
    security: [],
    utilities: [],
    landmarks: [],
    searchKeywords: [],
    promoTags: [],
  },
  {
    id: "mock-5",
    hash: "h5",
    title: "2 Bedroom Shortlet Apartment Lekki",
    listingUrl: "https://nigeriapropertycentre.com/listing/5",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SHORTLET",
    category: "SHORTLET",
    price: 80000,
    priceCurrency: "NGN",
    bedrooms: 2,
    bathrooms: 2,
    area: "Lekki Phase 1",
    state: "Lagos",
    country: "Nigeria",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Flat/Apartment",
    rentFrequency: "per night",
    description: "Tastefully furnished 2 bedroom shortlet apartment with Netflix, WiFi, and 24hr power. Perfect for business travelers and tourists.",
    features: ["WiFi", "Netflix", "Fully Furnished", "24hr Power", "Swimming Pool", "Gym"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800&auto=format&fit=crop"],
    agentVerified: true,
    viewCount: 320,
    inquiryCount: 45,
    favoriteCount: 110,
    isPremium: true,
    isFeatured: true,
    isHotDeal: true,
    currentVersion: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    qualityScore: 98,
    security: [],
    utilities: [],
    landmarks: [],
    searchKeywords: [],
    promoTags: [],
  },
  {
    id: "mock-6",
    hash: "h6",
    title: "1000sqm Land in Banana Island",
    listingUrl: "https://www.privateproperty.com.ng/listing/6",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "LAND",
    price: 600000000,
    priceCurrency: "NGN",
    area: "Banana Island",
    state: "Lagos",
    country: "Nigeria",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Residential Land",
    description: "Prime 1000sqm residential land in the prestigious Banana Island estate. Dry land with C of O. Perfect for luxury development.",
    features: ["C of O", "Dry Land", "Fenced"],
    landSizeSqm: 1000,
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop"],
    agentVerified: true,
    viewCount: 450,
    inquiryCount: 12,
    favoriteCount: 88,
    isPremium: true,
    isFeatured: true,
    isHotDeal: false,
    currentVersion: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    qualityScore: 90,
    security: [],
    utilities: [],
    landmarks: [],
    searchKeywords: [],
    promoTags: [],
  }
];
