import type { Property } from "@/types/property";

const createMockDate = (daysAgo = 0) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

const COMMON_DEFAULTS = {
  priceCurrency: "NGN",
  country: "Nigeria",
  agentVerified: true,
  viewCount: 0,
  inquiryCount: 0,
  favoriteCount: 0,
  currentVersion: 1,
  landmarks: [],
  security: [],
  utilities: [],
  searchKeywords: [],
  promoTags: [],
  isPremium: false,
  isFeatured: false,
  isHotDeal: false,
};

export const MOCK_PROPERTIES: Property[] = [
  {
    ...COMMON_DEFAULTS,
    id: "mock-1",
    hash: "h1",
    title: "Luxury 5 Bedroom Detached Duplex with BQ",
    listingUrl: "https://www.propertypro.ng/listing/1",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 150000000,
    bedrooms: 5,
    bathrooms: 5,
    area: "Lekki Phase 1",
    state: "Lagos",
    furnishing: "FURNISHED",
    condition: "NEW",
    propertyType: "Detached Duplex",
    description: "Exquisitely finished 5 bedroom detached duplex with swimming pool, BQ, and modern finishes throughout. Located in a serene estate in Lekki Phase 1.",
    features: ["Swimming Pool", "BQ", "Central AC", "CCTV", "Smart Home"],
    landSizeSqm: 600,
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=800&auto=format&fit=crop"],
    isPremium: true,
    isFeatured: true,
    isHotDeal: true,
    createdAt: createMockDate(5),
    updatedAt: createMockDate(1),
    qualityScore: 95,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-2",
    hash: "h2",
    title: "3 Bedroom Flat in Ikeja GRA",
    listingUrl: "https://nigeriapropertycentre.com/listing/2",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "RENT",
    category: "RESIDENTIAL",
    price: 3500000,
    bedrooms: 3,
    bathrooms: 3,
    area: "Ikeja GRA",
    state: "Lagos",
    furnishing: "SEMI_FURNISHED",
    condition: "GOOD",
    propertyType: "Flat/Apartment",
    rentFrequency: "per annum",
    description: "Well maintained 3 bedroom flat in a quiet cul-de-sac in Ikeja GRA. All rooms en-suite with fitted kitchen.",
    features: ["Fitted Kitchen", "24hr Power", "Security"],
    landSizeSqm: 150,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(10),
    updatedAt: createMockDate(2),
    qualityScore: 88,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-3",
    hash: "h3",
    title: "Brand New 4 Bedroom Semi-Detached Duplex",
    listingUrl: "https://www.privateproperty.com.ng/listing/3",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 85000000,
    bedrooms: 4,
    bathrooms: 4,
    area: "Ajah",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "NEW",
    propertyType: "Semi-Detached Duplex",
    description: "Brand new 4 bedroom semi-detached duplex in a gated estate. Quality finishes, spacious rooms, and excellent road network.",
    features: ["Gated Estate", "Paved Roads", "BQ", "Car Park"],
    landSizeSqm: 350,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop"],
    isPremium: true,
    createdAt: createMockDate(3),
    updatedAt: createMockDate(0),
    qualityScore: 92,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-4",
    hash: "h4",
    title: "Commercial Office Space in Victoria Island",
    listingUrl: "https://www.propertypro.ng/listing/4",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "LEASE",
    category: "COMMERCIAL",
    price: 15000000,
    area: "Victoria Island",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "GOOD",
    propertyType: "Office Space",
    rentFrequency: "per annum",
    description: "Premium office space on Adeola Odeku Street, Victoria Island. Open plan layout, 24/7 power, and dedicated parking.",
    features: ["24/7 Power", "Elevator", "Reception", "Conference Room", "Parking"],
    buildingSizeSqm: 500,
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop"],
    isFeatured: true,
    createdAt: createMockDate(15),
    updatedAt: createMockDate(5),
    qualityScore: 85,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-5",
    hash: "h5",
    title: "2 Bedroom Shortlet Apartment Lekki",
    listingUrl: "https://nigeriapropertycentre.com/listing/5",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SHORTLET",
    category: "SHORTLET",
    price: 80000,
    bedrooms: 2,
    bathrooms: 2,
    area: "Lekki Phase 1",
    state: "Lagos",
    furnishing: "FURNISHED",
    condition: "GOOD",
    propertyType: "Flat/Apartment",
    rentFrequency: "per night",
    description: "Tastefully furnished 2 bedroom shortlet apartment with Netflix, WiFi, and 24hr power. Perfect for business travelers and tourists.",
    features: ["WiFi", "Netflix", "Fully Furnished", "24hr Power", "Swimming Pool", "Gym"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800&auto=format&fit=crop"],
    isPremium: true,
    isFeatured: true,
    isHotDeal: true,
    createdAt: createMockDate(2),
    updatedAt: createMockDate(0),
    qualityScore: 98,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-6",
    hash: "h6",
    title: "1000sqm Land in Banana Island",
    listingUrl: "https://www.privateproperty.com.ng/listing/6",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "LAND",
    price: 600000000,
    area: "Banana Island",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "UNKNOWN",
    propertyType: "Residential Land",
    description: "Prime 1000sqm residential land in the prestigious Banana Island estate. Dry land with C of O. Perfect for luxury development.",
    features: ["C of O", "Dry Land", "Fenced"],
    landSizeSqm: 1000,
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop"],
    isPremium: true,
    isFeatured: true,
    createdAt: createMockDate(30),
    updatedAt: createMockDate(10),
    qualityScore: 90,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-7",
    hash: "h7",
    title: "Serviced 3 Bedroom Flat with Pool",
    listingUrl: "https://www.propertypro.ng/listing/7",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 65000000,
    bedrooms: 3,
    bathrooms: 3,
    area: "Ikoyi",
    state: "Lagos",
    furnishing: "SEMI_FURNISHED",
    condition: "GOOD",
    propertyType: "Flat/Apartment",
    description: "Beautifully finished 3 bedroom serviced flat in Ikoyi with swimming pool, gym, and 24/7 security.",
    features: ["Swimming Pool", "Gym", "24hr Security", "Elevator", "Fitted Kitchen"],
    buildingSizeSqm: 200,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(8),
    updatedAt: createMockDate(2),
    qualityScore: 91,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-8",
    hash: "h8",
    title: "Warehouse for Lease in Apapa",
    listingUrl: "https://nigeriapropertycentre.com/listing/8",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "LEASE",
    category: "INDUSTRIAL",
    price: 25000000,
    area: "Apapa",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "GOOD",
    propertyType: "Warehouse",
    rentFrequency: "per annum",
    description: "Large warehouse space in Apapa industrial zone. High ceilings, loading bays, and good access roads. Suitable for logistics and storage.",
    features: ["Loading Bay", "High Ceiling", "Security", "Office Space"],
    buildingSizeSqm: 2000,
    images: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(20),
    updatedAt: createMockDate(5),
    qualityScore: 82,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-9",
    hash: "h9",
    title: "Newly Built 4 Bedroom Terrace in Chevron",
    listingUrl: "https://www.privateproperty.com.ng/listing/9",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 55000000,
    bedrooms: 4,
    bathrooms: 4,
    area: "Chevron",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "NEW",
    propertyType: "Terrace Duplex",
    description: "Newly built 4 bedroom terrace duplex in Chevron area. Smart home features, all rooms en-suite, fitted kitchen with island.",
    features: ["Smart Home", "Fitted Kitchen", "BQ", "CCTV", "Interlocked Compound"],
    landSizeSqm: 250,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(4),
    updatedAt: createMockDate(1),
    qualityScore: 89,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-10",
    hash: "h10",
    title: "2 Bedroom Flat for Rent in Yaba",
    listingUrl: "https://www.propertypro.ng/listing/10",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "RENT",
    category: "RESIDENTIAL",
    price: 1800000,
    bedrooms: 2,
    bathrooms: 2,
    area: "Yaba",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "GOOD",
    propertyType: "Flat/Apartment",
    rentFrequency: "per annum",
    description: "Clean and spacious 2 bedroom flat in Yaba. Close to major tech hubs and universities. Good water supply and steady power.",
    features: ["Water Supply", "Prepaid Meter", "Pop Ceiling"],
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(12),
    updatedAt: createMockDate(3),
    qualityScore: 80,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-11",
    hash: "h11",
    title: "500sqm Commercial Land in Lekki",
    listingUrl: "https://nigeriapropertycentre.com/listing/11",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "LAND",
    price: 120000000,
    area: "Lekki",
    state: "Lagos",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Commercial Land",
    description: "Strategic 500sqm commercial land on the Lekki-Epe Expressway. Ideal for shopping complex, hotel, or mixed-use development. Gazette and C of O available.",
    features: ["C of O", "Gazette", "Road Facing", "Dry Land"],
    landSizeSqm: 500,
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(25),
    updatedAt: createMockDate(8),
    qualityScore: 86,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-12",
    hash: "h12",
    title: "Penthouse Suite in Eko Atlantic",
    listingUrl: "https://www.privateproperty.com.ng/listing/12",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 450000000,
    bedrooms: 4,
    bathrooms: 5,
    area: "Eko Atlantic",
    state: "Lagos",
    furnishing: "FURNISHED",
    condition: "NEW",
    propertyType: "Penthouse",
    description: "Ultra-luxury penthouse in Eko Atlantic with panoramic ocean views. Italian marble finishes, private elevator, rooftop terrace, and smart home automation.",
    features: ["Ocean View", "Private Elevator", "Rooftop Terrace", "Smart Home", "Marble Finishes", "Wine Cellar", "Home Cinema"],
    buildingSizeSqm: 450,
    images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(1),
    updatedAt: createMockDate(0),
    qualityScore: 99,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-13",
    hash: "h13",
    title: "Studio Apartment Shortlet Victoria Island",
    listingUrl: "https://www.propertypro.ng/listing/13",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SHORTLET",
    category: "SHORTLET",
    price: 50000,
    bedrooms: 1,
    bathrooms: 1,
    area: "Victoria Island",
    state: "Lagos",
    furnishing: "FURNISHED",
    condition: "GOOD",
    propertyType: "Studio",
    rentFrequency: "per night",
    description: "Cozy studio apartment in the heart of Victoria Island. Fully furnished with modern amenities. Walking distance to bars and restaurants.",
    features: ["WiFi", "Netflix", "Air Conditioning", "Fully Furnished", "24hr Power"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(6),
    updatedAt: createMockDate(1),
    qualityScore: 84,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-14",
    hash: "h14",
    title: "6 Bedroom Mansion with Cinema",
    listingUrl: "https://nigeriapropertycentre.com/listing/14",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 350000000,
    bedrooms: 6,
    bathrooms: 7,
    area: "Ikoyi",
    state: "Lagos",
    furnishing: "FURNISHED",
    condition: "GOOD",
    propertyType: "Detached Duplex",
    description: "Magnificent 6 bedroom mansion in Old Ikoyi. Features include home cinema, wine cellar, infinity pool, and staff quarters. Sits on 1200sqm of land.",
    features: ["Home Cinema", "Wine Cellar", "Infinity Pool", "Staff Quarters", "Garden", "CCTV", "Central AC"],
    landSizeSqm: 1200,
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(15),
    updatedAt: createMockDate(5),
    qualityScore: 97,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-15",
    hash: "h15",
    title: "3 Bedroom Bungalow in Magodo",
    listingUrl: "https://www.privateproperty.com.ng/listing/15",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 45000000,
    bedrooms: 3,
    bathrooms: 2,
    area: "Magodo",
    state: "Lagos",
    furnishing: "SEMI_FURNISHED",
    condition: "GOOD",
    propertyType: "Bungalow",
    description: "Well-built 3 bedroom bungalow in Magodo Phase 2. Spacious compound with room for expansion. Family-friendly neighborhood with good schools nearby.",
    features: ["Spacious Compound", "BQ", "Car Park", "Water Borehole"],
    landSizeSqm: 500,
    images: ["https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(22),
    updatedAt: createMockDate(7),
    qualityScore: 83,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-16",
    hash: "h16",
    title: "Shop Space in Computer Village",
    listingUrl: "https://www.propertypro.ng/listing/16",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "RENT",
    category: "COMMERCIAL",
    price: 2500000,
    area: "Computer Village, Ikeja",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "GOOD",
    propertyType: "Shop",
    rentFrequency: "per annum",
    description: "Well-positioned shop space in Computer Village, Ikeja. High foot traffic area, perfect for electronics retail. Ground floor with good frontage.",
    features: ["Ground Floor", "Good Frontage", "High Traffic"],
    buildingSizeSqm: 30,
    images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(18),
    updatedAt: createMockDate(4),
    qualityScore: 78,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-17",
    hash: "h17",
    title: "4 Bedroom Duplex with Pool in Sangotedo",
    listingUrl: "https://nigeriapropertycentre.com/listing/17",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "RESIDENTIAL",
    price: 70000000,
    bedrooms: 4,
    bathrooms: 5,
    area: "Sangotedo",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "NEW",
    propertyType: "Detached Duplex",
    description: "Modern 4 bedroom detached duplex with private pool in a secure estate in Sangotedo. Close to Shoprite and major amenities.",
    features: ["Swimming Pool", "BQ", "Gated Estate", "Fitted Kitchen", "CCTV"],
    landSizeSqm: 400,
    images: ["https://images.unsplash.com/photo-1600566752355-397921137bf1?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(7),
    updatedAt: createMockDate(1),
    qualityScore: 90,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-18",
    hash: "h18",
    title: "1 Bedroom Mini Flat in Surulere",
    listingUrl: "https://www.privateproperty.com.ng/listing/18",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "RENT",
    category: "RESIDENTIAL",
    price: 800000,
    bedrooms: 1,
    bathrooms: 1,
    area: "Surulere",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "FAIR",
    propertyType: "Mini Flat",
    rentFrequency: "per annum",
    description: "Newly renovated 1 bedroom mini flat in Surulere. Tiled floors, modern fittings, and prepaid meter. Close to the National Stadium.",
    features: ["Prepaid Meter", "Tiled", "Water Supply"],
    images: ["https://images.unsplash.com/photo-1536376074432-bf7244976d3d?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(14),
    updatedAt: createMockDate(3),
    qualityScore: 75,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-19",
    hash: "h19",
    title: "Mixed-Use Development Land Ibeju-Lekki",
    listingUrl: "https://www.propertypro.ng/listing/19",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "LAND",
    price: 35000000,
    area: "Ibeju-Lekki",
    state: "Lagos",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Mixed-Use Land",
    description: "2000sqm of land in Ibeju-Lekki free trade zone area. Excellent for mixed-use development. Close to Dangote Refinery and new airport project.",
    features: ["Gazette", "Survey Plan", "Free Trade Zone"],
    landSizeSqm: 2000,
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(45),
    updatedAt: createMockDate(15),
    qualityScore: 82,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-20",
    hash: "h20",
    title: "3 Bedroom Shortlet with Rooftop Terrace",
    listingUrl: "https://nigeriapropertycentre.com/listing/20",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SHORTLET",
    category: "SHORTLET",
    price: 120000,
    bedrooms: 3,
    bathrooms: 3,
    area: "Lekki Phase 1",
    state: "Lagos",
    furnishing: "FURNISHED",
    condition: "GOOD",
    propertyType: "Penthouse",
    rentFrequency: "per night",
    description: "Stunning 3 bedroom shortlet penthouse with rooftop terrace and BBQ area. Perfect for events and getaways. Fully smart home enabled.",
    features: ["Rooftop Terrace", "BBQ Area", "Smart Home", "Netflix", "WiFi", "Pool", "Gym", "Fully Furnished"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(3),
    updatedAt: createMockDate(0),
    qualityScore: 96,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-21",
    hash: "h21",
    title: "Co-working Space in Ikeja",
    listingUrl: "https://www.privateproperty.com.ng/listing/21",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "LEASE",
    category: "COMMERCIAL",
    price: 500000,
    area: "Ikeja",
    state: "Lagos",
    furnishing: "FURNISHED",
    condition: "GOOD",
    propertyType: "Co-working Space",
    rentFrequency: "per month",
    description: "Flexible co-working space in the heart of Ikeja. Includes high-speed internet, coffee, and meeting rooms.",
    features: ["WiFi", "Coffee", "Meeting Rooms", "24/7 Access"],
    buildingSizeSqm: 100,
    images: ["https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(10),
    updatedAt: createMockDate(2),
    qualityScore: 88,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-22",
    hash: "h22",
    title: "Luxury Beachfront Land in Ilashe",
    listingUrl: "https://www.propertypro.ng/listing/22",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "LAND",
    price: 45000000,
    area: "Ilashe",
    state: "Lagos",
    furnishing: "UNKNOWN",
    condition: "UNKNOWN",
    propertyType: "Beachfront Land",
    description: "Exclusive beachfront land in Ilashe. Ideal for building a private luxury beach resort or getaway villa. Pristine white sand and ocean views.",
    features: ["Beachfront", "Ocean View", "Pristine Sand"],
    landSizeSqm: 1500,
    images: ["https://images.unsplash.com/photo-1544885935-98dd03b0c73d?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(50),
    updatedAt: createMockDate(20),
    qualityScore: 92,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-23",
    hash: "h23",
    title: "Modern 2 Bedroom Apartment in Maryland",
    listingUrl: "https://nigeriapropertycentre.com/listing/23",
    source: "nigeriapropertycentre",
    siteId: "s2",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "RENT",
    category: "RESIDENTIAL",
    price: 2500000,
    bedrooms: 2,
    bathrooms: 2,
    area: "Maryland",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "GOOD",
    propertyType: "Flat/Apartment",
    rentFrequency: "per annum",
    description: "Tastefully finished 2 bedroom apartment in a secure gated community in Maryland. Includes fitted kitchen and modern wardrobes.",
    features: ["Fitted Kitchen", "Wardrobes", "Secure Estate"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800&auto=format&fit=crop"],
    createdAt: createMockDate(9),
    updatedAt: createMockDate(2),
    qualityScore: 87,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-24",
    hash: "h24",
    title: "Prime Office Block in Gbagada",
    listingUrl: "https://www.privateproperty.com.ng/listing/24",
    source: "privateproperty",
    siteId: "s3",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SALE",
    category: "COMMERCIAL",
    price: 250000000,
    area: "Gbagada",
    state: "Lagos",
    furnishing: "UNFURNISHED",
    condition: "GOOD",
    propertyType: "Office Block",
    description: "Strategy office block for sale in Gbagada Phase 2. Five floors of open-plan office space with basement parking.",
    features: ["Basement Parking", "Open Plan", "Prime Location"],
    buildingSizeSqm: 1200,
    images: ["https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800&auto=format&fit=crop"],
    isFeatured: true,
    createdAt: createMockDate(60),
    updatedAt: createMockDate(10),
    qualityScore: 93,
  },
  {
    ...COMMON_DEFAULTS,
    id: "mock-25",
    hash: "h25",
    title: "Executive Shortlet in Ikoyi",
    listingUrl: "https://www.propertypro.ng/listing/25",
    source: "propertypro",
    siteId: "s1",
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    listingType: "SHORTLET",
    category: "SHORTLET",
    price: 150000,
    bedrooms: 2,
    bathrooms: 2,
    area: "Old Ikoyi",
    state: "Lagos",
    furnishing: "FURNISHED",
    condition: "GOOD",
    propertyType: "Flat/Apartment",
    rentFrequency: "per night",
    description: "Premium 2 bedroom executive shortlet in Old Ikoyi. Feature high-end Italian furniture, chef-service, and car hire options.",
    features: ["Chef Service", "Car Hire", "Italian Furniture", "Gym", "Pool"],
    images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=800&auto=format&fit=crop"],
    isPremium: true,
    createdAt: createMockDate(0),
    updatedAt: createMockDate(0),
    qualityScore: 96,
  }
];
